### ISSUE TITLE
Overlap with BeTrains.bash?

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/command-irail#1]
One of our oldest repos: https://github.com/iRail/BeTrains.Bash

It's quite close to that one? Yet I'm curious what you're going to code here :)

**Comment by barbarosso** [comment]
@pietercolpaert There's a first draft on develop.
For the moment you will need node v7.7.1. 
https://github.com/iRail/command-irail/tree/develop
Feedback is welcome :-)

**Comment by barbarosso** [comment]
@pietercolpaert I finally published the first version on npm.
You can install it via npm i command-irail -g
usage: irail [-h] [-v] [-l]
Optional arguments:
  -h, --help     Show this help message and exit.
  -v, --version  Show program's version number and exit.
  -l, --last     repeats last searched route

**Comment by derhuerst** [comment]
FYI:

[`vbb-cli`](https://www.npmjs.com/package/vbb-cli) had a lot of code not specifically related to Berlin, but to HAFAS endpoints in general. I moved this general code into [`hafas-cli`](https://www.npmjs.com/package/hafas-cli).

Maybe you can make use of it. On the other hand, the API interface it expects is very specific.
